# Automatically generated by ./configure
# Command line: --with-system-malloc --allow-fetch
CONFIGURE_STATUS := started
CONFIGURE_ERROR := 
CONFIGURE_COMMAND_LINE := --fetch re2 --fetch gtest --fetch v8 --fetch jemalloc --with-system-malloc --allow-fetch
CONFIGURE_MAGIC_NUMBER := 2
# Bash
FETCH_LIST := 
FETCH_VERSIONS := 
LIB_SEARCH_PATHS := 
# Use ccache
USE_CCACHE := 0
# C++ Compiler
COMPILER := GCC
CXX := /usr/bin/c++
# Host System
MACHINE := arm-linux-gnueabihf
# Build System
# Cross-compiling
CROSS_COMPILING := 0
# Host Operating System
OS := Linux
PTHREAD_LIBS := -pthread
RT_LIBS := -lrt
LDFLAGS += -ldl
M_LIBS := -lm
# Build Architecture
GCC_ARCH := armv7l
GCC_ARCH_REDUCED := armv7l
# C++11
CXX11_LIBS += 
HAS_CXX11 := 1
# Precompiled web assets
USE_PRECOMPILED_WEB_ASSETS := 1
# Protobuf compiler
FETCH_LIST += protobuf
protobuf_VERSION := 2.5.0
protobuf_DEPENDS := 
PROTOC = $(abspath $(SUPPORT_BUILD_DIR)/protobuf_2.5.0/bin/protoc)
PROTOC_BIN_DEP = $(SUPPORT_BUILD_DIR)/protobuf_2.5.0/bin/protoc
# python
PYTHON := /usr/bin/python
PYTHON_BIN_DEP := 
# Node.js package manager
NPM := /usr/bin/npm
NPM_BIN_DEP := 
# coffee
FETCH_LIST += coffee-script
coffee-script_VERSION := 1.10.0
coffee-script_DEPENDS := 
COFFEE = $(abspath $(SUPPORT_BUILD_DIR)/coffee-script_1.10.0/bin/coffee)
COFFEE_BIN_DEP = $(SUPPORT_BUILD_DIR)/coffee-script_1.10.0/bin/coffee
# Browserify
FETCH_LIST += browserify
browserify_VERSION := 13.1.0
browserify_DEPENDS := 
BROWSERIFY = $(abspath $(SUPPORT_BUILD_DIR)/browserify_13.1.0/bin/browserify)
BROWSERIFY_BIN_DEP = $(SUPPORT_BUILD_DIR)/browserify_13.1.0/bin/browserify
# bluebird
FETCH_LIST += bluebird
bluebird_VERSION := 2.9.32
bluebird_DEPENDS := 
BLUEBIRD = $(abspath $(SUPPORT_BUILD_DIR)/bluebird_2.9.32/bin/bluebird)
BLUEBIRD_BIN_DEP = $(SUPPORT_BUILD_DIR)/bluebird_2.9.32/bin/bluebird
# web UI dependencies
FETCH_LIST += admin-deps
admin-deps_VERSION := 2.0.3
admin-deps_DEPENDS := 
GULP = $(abspath $(SUPPORT_BUILD_DIR)/admin-deps_2.0.3/bin/gulp)
GULP_BIN_DEP = $(SUPPORT_BUILD_DIR)/admin-deps_2.0.3/bin/gulp
# wget
WGET := /usr/bin/wget
WGET_BIN_DEP := 
# curl
CURL := /usr/bin/curl
CURL_BIN_DEP := 
# Google Test
FETCH_LIST += gtest
gtest_VERSION := 1.7.0
gtest_DEPENDS := 
gtest_LIB_NAME += GTEST
HAS_GTEST := 1
GTEST_LIBS_DEP = $(SUPPORT_BUILD_DIR)/gtest_1.7.0/lib/libgtest.a
GTEST_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/gtest_1.7.0/include
GTEST_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/gtest_1.7.0/include
# termcap
HAS_TERMCAP := 0
TERMCAP_LIBS := 
TERMCAP_INCLUDE := 
TERMCAP_INCLUDE_DEP := 
TERMCAP_LIBS_DEP := 
# boost_system
FETCH_LIST += boost
boost_VERSION := 1.56.0
boost_DEPENDS := 
boost_LIB_NAME += BOOST_SYSTEM
HAS_BOOST_SYSTEM := 1
BOOST_SYSTEM_LIBS_DEP = $(SUPPORT_BUILD_DIR)/boost_1.56.0/lib/libboost_system.a
BOOST_SYSTEM_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/boost_1.56.0/include
BOOST_SYSTEM_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/boost_1.56.0/include
# Protobuf library
protobuf_LIB_NAME += PROTOBUF
HAS_PROTOBUF := 1
PROTOBUF_LIBS_DEP = $(SUPPORT_BUILD_DIR)/protobuf_2.5.0/lib/libprotobuf.a
PROTOBUF_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/protobuf_2.5.0/include
PROTOBUF_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/protobuf_2.5.0/include
# v8 javascript engine
FETCH_LIST += v8
v8_VERSION := 3.30.33.16-patched2
v8_DEPENDS := 
v8_LIB_NAME += V8
HAS_V8 := 1
V8_LIBS_DEP = $(SUPPORT_BUILD_DIR)/v8_3.30.33.16-patched2/lib/libv8.a
V8_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/v8_3.30.33.16-patched2/include
V8_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/v8_3.30.33.16-patched2/include
# RE2
FETCH_LIST += re2
re2_VERSION := 20140111
re2_DEPENDS := 
re2_LIB_NAME += RE2
HAS_RE2 := 1
RE2_LIBS_DEP = $(SUPPORT_BUILD_DIR)/re2_20140111/lib/libre2.a
RE2_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/re2_20140111/include
RE2_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/re2_20140111/include
# z
Z_LIBS += -lz
HAS_Z := 1
HAS_Z := 1
Z_INCLUDE := 
Z_INCLUDE_DEP := 
Z_LIBS_DEP := 
# crypto
FETCH_LIST += openssl
openssl_VERSION := 1.0.1t
openssl_DEPENDS := 
openssl_LIB_NAME += CRYPTO
HAS_CRYPTO := 1
CRYPTO_LIBS_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/lib/libcrypto.a
CRYPTO_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/include
CRYPTO_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/lib/libcrypto.a
# ssl
openssl_LIB_NAME += SSL
HAS_SSL := 1
SSL_LIBS_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/lib/libssl.a
SSL_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/include
SSL_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/lib/libssl.a
# curl
CURL_LIBS += -lcurl
HAS_CURL := 1
HAS_CURL := 1
CURL_INCLUDE := 
CURL_INCLUDE_DEP := 
CURL_LIBS_DEP := 
V8_PRE_3_19 := 0
# malloc
ALLOCATOR := system
DEFAULT_ALLOCATOR := jemalloc
MALLOC_LIBS := 
MALLOC_LIBS_DEP := 
STATIC_MALLOC := 0
# Test protobuf
PROTOC = $(abspath $(SUPPORT_BUILD_DIR)/protobuf_2.5.0/bin/protoc)
PROTOC_BIN_DEP = $(SUPPORT_BUILD_DIR)/protobuf_2.5.0/bin/protoc
# Test boost
boost_LIB_NAME += BOOST
HAS_BOOST := 1
BOOST_LIBS_DEP = $(SUPPORT_BUILD_DIR)/boost_1.56.0/lib/libboost.a
BOOST_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/boost_1.56.0/include
BOOST_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/boost_1.56.0/include
# Test OpenSSL
openssl_LIB_NAME += OPENSSL
HAS_OPENSSL := 1
OPENSSL_LIBS_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/lib/libopenssl.a
OPENSSL_INCLUDE = -isystem $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/include
OPENSSL_INCLUDE_DEP = $(SUPPORT_BUILD_DIR)/openssl_1.0.1t/lib/libopenssl.a
STATIC_V8 := 1
ALLOW_FETCH := 1
# Installation prefix
PREFIX := /usr/local
# Configuration prefix
SYSCONFDIR := /usr/local/etc
# Runtime data prefix
LOCALSTATEDIR := /usr/local/var
CONFIGURE_STATUS := success
